version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27018/oz-tech-test
  mongo:
    image: mongo
    ports:
      - '27018:27017'